spring.application.name=MyFirstApp

spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.test2.jdbcUrl=jdbc:mysql://localhost:3306/test
spring.datasource.test2.username=root
spring.datasource.test2.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect