debug=true
logging.level.org.springframework.boot.autoconfigure=TRACE

spring.application.name=MyFirstApp
logging.level.com.example.myfirstapp=INFO

spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.test2.jdbc-url=jdbc:mysql://localhost:3306/sakila
spring.datasource.test2.username=root
spring.datasource.test2.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

kafka.cluster1.bootstrap-servers=localhost:9092,localhost:9093,localhost:9094
kafka.cluster2.bootstrap-servers=localhost:9092,localhost:9093,localhost:9094

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer